[package]
name = "maxoning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
bevy_asset_loader = { version = "0.17.0", features = ["2d", "3d", "standard_dynamic_assets"] }
bevy_common_assets = { version = "0.7.0", features = ["json"] }
serde = { version = "1.0.189", features = ["derive"] }
