[package]
name = "maxoning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
bevy-inspector-egui = "0.21.0"
bevy-persistent = { version = "0.4.0", features = ["json"] }
bevy_asset_loader = { version = "0.18.0", features = ["2d", "3d", "standard_dynamic_assets"] }
bevy_common_assets = { version = "0.8.0", features = ["json"] }
dirs = "5.0.1"
serde = { version = "1.0.189", features = ["derive"] }
